// <auto-generated />
namespace SecuritySystemAPI.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Addedsensordatatable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Addedsensordatatable));
        
        string IMigrationMetadata.Id
        {
            get { return "201610230103310_Added sensor data table."; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
